### ISSUE TITLE
inputbox输入内容后还是有 placeholder

### ISSUE THREAD

**Issue by masquevil** [eisneim/angular-ui-awesome#1]
http://eisneim.github.io/angular-ui-awesome/#/component/inputBox
看的这个页面，输入内容后，失焦还是会有 placeholder

**Comment by eisneim** [comment]
目前只在chrome中开发和测试，暂无时间开发。。。

**Comment by zhougonglai** [comment]
这么好用的框架还是希望 老板能够 开发完结...
